### ISSUE TITLE
TypeError: run is not a function

### ISSUE THREAD

**Issue by dragonfleas** [github/local-action#104]
# Description

I'm running `Version: 2.1.2` of local-action

I just installed local-action on a semi-fresh template project, and when I try to run the action with it, it dumps this error:
```
/home/user/nvm/versions/node/v21.7.1/lib/node_modules/@github/local-action/src/commands/run.ts:153
    await run()
          ^


TypeError: run is not a function
    at action (/home/user/.nvm/versions/node/v21.7.1/lib/node_modules/@github/local-action/src/commands/run.ts:153:11)
    at Command.<anonymous> (/home/user/.nvm/versions/node/v21.7.1/lib/node_modules/@github/local-action/src/command.ts:112:7)

Node.js v21.7.1
```

This is my package json dependencies for reference

```
  "dependencies": {
    "@actions/core": "^1.10.1",
    "ajv": "^8.17.1",
    "ajv-formats": "^3.0.1"
  },
  "devDependencies": {
    "@eslint/eslintrc": "^3.1.0",
    "@eslint/js": "^9.10.0",
    "@jest/globals": "^29.7.0",
    "@types/eslint__js": "^8.42.3",
    "@types/jest": "^29.5.13",
    "@types/node": "^22.5.5",
    "@typescript-eslint/eslint-plugin": "^8.5.0",
    "@typescript-eslint/parser": "^8.5.0",
    "@vercel/ncc": "^0.38.1",
    "eslint": "^9.10.0",
    "eslint-plugin-jest": "^28.8.3",
    "eslint-plugin-jsonc": "^2.16.0",
    "eslint-plugin-prettier": "^5.2.1",
    "globals": "^15.9.0",
    "jest": "^29.7.0",
    "make-coverage-badge": "^1.2.0",
    "prettier": "^3.3.3",
    "prettier-eslint": "^16.3.0",
    "ts-jest": "^29.2.5",
    "typescript": "^5.6.2",
    "typescript-eslint": "^8.5.0"
  }
```

**Comment by ncalteen** [comment]
@dragonfleas Are you able to provide a link to a repository where I can reproduce this? I'm pretty sure it has to do with the entrypoint path, but need to verify against the structure of the repo.

**Comment by dragonfleas** [comment]
> @dragonfleas Are you able to provide a link to a repository where I can reproduce this? I'm pretty sure it has to do with the entrypoint path, but need to verify against the structure of the repo.

https://github.com/dragonfleas/upload-sarif

**Comment by ncalteen** [comment]
When you run `local-action` are you passing `src/index.ts` or `src/main.ts` for the second parameter? This error normally occurs when you pass `src/index.ts`, importing that will immediately attempt to run the action (before `local-action` has a chance to stub anything.

When I try the following on a local clone of your repo, it looks like it is working correctly.

```bash
npx local-action . src/main.ts .env
```

Output:

```plain
================================================================================
                                 Running Action
================================================================================
::debug::Processing SARIF file ../results
::debug::Error validating SARIF file: ENOENT: no such file or directory, open '../results'
::error::SARIF file is not valid
::error::SARIF file is not valid
```

**Comment by dragonfleas** [comment]
Ah, I think that was it, thank you! I thought it needed to be run at the
entrypoint and that it should work as long as it wasn't the transpiled
code. That clarifies things well.

**Comment by ncalteen** [comment]
Glad to hear it worked!

I am going to make a tweak to include some more useful error output when this situation occurs :)
