### ISSUE TITLE
Add a little example to readme for why allowJs is required

### ISSUE THREAD

**Issue by pitoniak32** [github/local-action#120]
I was fighting an error and couldn't find anyone seeing the same issue as me anywhere. It turned out I had allowJs true in my tsconfig.

The error:
```
TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
...
```
This occurred when using the local-action but not when running the built JavaScript. 

My proposal is add a section to "TsConfig Requirements". I would be more than happy to make a PR if it's welcomed!

### Troubleshooting
Possible errors that can arise if these settings are incorrect
- ...

**Comment by ncalteen** [comment]
Yeah I'm ashamed to say how long it took me to figure that problem out too...

I did add a small snippet [here](https://github.com/github/local-action?tab=readme-ov-file#typescript-tsconfig-requirements), however if you'd like to expand on that a PR is more than welcome!

**Comment by pitoniak32** [comment]
crated a pr adding the extra details!

**Comment by ncalteen** [comment]
Sorry I was OOO for a couple weeks and forgot to check this! One small tweak in the PR but I appreciate the input!
