### ISSUE TITLE
npm says 404 Not Found when installing via @github/local-action

### ISSUE THREAD

**Issue by morphine00** [github/local-action#25]
Hi there!

As per the README, I'm trying to install `local-action` via `npm`. However, after logging in to GitHub packages and running `npm i -g @github/local-action` I get:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@github%2flocal-action - Not found
npm ERR! 404
npm ERR! 404  '@github/local-action@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by ncalteen** [comment]
It looks like your `.npmrc` is still pointing to `registry.npmjs.org`. However, I'm going to work on also publishing this to npm so that it's more easily accessible :)

**Comment by morphine00** [comment]
Oh I see. That would be great, thanks for the feedback.

**Comment by ncalteen** [comment]
👋  Just letting you know the package has been removed from GitHub Packages and published to npm directly!

https://www.npmjs.com/package/@github/local-action

Closing this issue out :)
